export default [
  {
    path: '/me-agreement',
    name: 'Agreement',
    component: () => import('@/pages/me/meAgreement.vue'),
    meta: { title: '软件许可与服务协议' },
  },
  {
    path: '/me-about',
    name: 'MeAbout',
    component: () => import('@/pages/me/me-about.vue'),
    meta: { title: '关于' },
  },
  {
    path: '/me-conceal',
    name: 'MeConceal',
    component: () => import('@/pages/me/meConceal.vue'),
    meta: { title: '隐私' },
  },
  {
    path: '/me-house',
    name: 'MeHouse',
    component: () => import('@/pages/me/meHouse.vue'),
    meta: { title: '家庭管理' },
  },
  {
    path: '/me-house-name',
    name: 'MeHouseName',
    component: () => import('@/pages/me/meHouseName.vue'),
    meta: { title: '家庭名称' },
  },
  {
    path: '/me-house-map',
    name: 'MeHouseMap',
    component: () => import('@/pages/me/meHouseMap.vue'),
    meta: { title: '家庭位置' },
  },
  {
    path: '/me-house-memberList',
    name: 'MeHouseMemberList',
    component: () => import('@/pages/me/meHouseMemberList.vue'),
    meta: { title: '成员与权限' },
  },
  {
    path: '/me-house-memberItem',
    name: 'MeHouseMemberItem',
    component: () => import('@/pages/me/meHouseMemberItem.vue'),
    meta: { title: '家庭权限' },
  },
  {
    path: '/me-room-manage',
    name: 'MeRoomManage',
    component: () => import('@/pages/me/meRoomManage.vue'),
    meta: { title: '房间管理' },
  },
  {
    path: '/me-house-create',
    name: 'MeHouseCreate',
    component: () => import('@/pages/me/meHouseCreate.vue'),
    meta: { title: '创建家庭' },
  },
  {
    path: '/me-info',
    name: 'MeInfo',
    component: () => import('@/pages/me/meInfo.vue'),
    meta: { title: '个人信息' },
  },
  {
    path: '/meNickname',
    name: 'MeNickname',
    component: () => import('@/pages/me/meNickname.vue'),
    meta: { title: '昵称' },
  },
  {
    path: '/me-phone-change',
    name: 'MePhoneChange',
    component: () => import('@/pages/me/mePhoneChange.vue'),
    meta: { title: '更换手机号' },
  },
  {
    path: '/me-password-change',
    name: 'MePasswordChange',
    component: () => import('@/pages/me/mePasswordChange.vue'),
    meta: { title: '修改密码' },
  },
  {
    path: '/me-development',
    name: 'MeDevelopment',
    component: () => import('@/pages/me/meDevelopment.vue'),
    meta: { title: '开发者模式' },
  },
]
