export default [
  {
    path: '/me-setting',
    name: 'MeSetting',
    component: () => import('@/pages/me/me-setting.vue'),
    meta: { title: '设置' },
  },
  {
    path: '/me-agreement',
    name: 'MeAgreement',
    component: () => import('@/pages/me/me-agreement.vue'),
    meta: { title: '软件许可与服务协议' },
  },
  {
    path: '/me-about',
    name: 'MeAbout',
    component: () => import('@/pages/me/me-about.vue'),
    meta: { title: '关于' },
  },
  {
    path: '/me-conceal',
    name: 'MeConceal',
    component: () => import('@/pages/me/me-conceal.vue'),
    meta: { title: '隐私' },
  },
  {
    path: '/me-house-list',
    name: 'MeHouseList',
    component: () => import('@/pages/me/me-house-list.vue'),
    meta: { title: '家庭列表' },
  },
  {
    path: '/me-house-item',
    name: 'MeHouse',
    component: () => import('@/pages/me/me-house-item.vue'),
    meta: { title: '家庭管理' },
  },
  {
    path: '/me-house-name',
    name: 'MeHouseName',
    component: () => import('@/pages/me/me-house-name.vue'),
    meta: { title: '家庭名称' },
  },
  {
    path: '/me-house-map',
    name: 'MeHouseMap',
    component: () => import('@/pages/me/me-house-map.vue'),
    meta: { title: '家庭位置' },
  },
  {
    path: '/me-house-invite',
    name: 'MeHouseInvite',
    component: () => import('@/pages/me/me-house-invite.vue'),
    meta: { title: '成员列表', keepAlive: true },
  },
  {
    path: '/me-house-member-item',
    name: 'MeHouseMemberItem',
    component: () => import('@/pages/me/me-house-member-item.vue'),
    meta: { title: '成员信息' },
  },
  {
    path: '/me-house-member-remark',
    name: 'MeHouseMemberRemark',
    component: () => import('@/pages/me/me-house-member-remark.vue'),
    meta: { title: '成员备注名' },
  },
  {
    path: '/me-house-powers',
    name: 'MeHousePowers',
    component: () => import('@/pages/me/me-house-powers.vue'),
    meta: { title: '家庭权限' },
  },
  {
    path: '/me-room-manage',
    name: 'MeRoomManage',
    component: () => import('@/pages/me/me-room-manage.vue'),
    meta: { title: '房间管理' },
  },
  {
    path: '/me-house-create',
    name: 'MeHouseCreate',
    component: () => import('@/pages/me/me-house-create.vue'),
    meta: { title: '创建家庭' },
  },
  {
    path: '/me-info',
    name: 'MeInfo',
    component: () => import('@/pages/me/me-info.vue'),
    meta: { title: '个人信息' },
  },
  {
    path: '/me-nickname',
    name: 'MeNickname',
    component: () => import('@/pages/me/me-nickname.vue'),
    meta: { title: '昵称' },
  },
  {
    path: '/me-phone-change',
    name: 'MePhoneChange',
    component: () => import('@/pages/me/me-phone-change.vue'),
    meta: { title: '更换手机号' },
  },
  {
    path: '/me-password-change',
    name: 'MePasswordChange',
    component: () => import('@/pages/me/me-password-change.vue'),
    meta: { title: '修改密码' },
  },
  {
    path: '/me-not-password',
    name: 'meNotPassword',
    component: () => import('@/pages/me/me-not-password.vue'),
    meta: { title: '首次设置密码' },
  },
  {
    path: '/me-development',
    name: 'MeDevelopment',
    component: () => import('@/pages/me/me-development.vue'),
    meta: { title: '开发者模式' },
  },
  {
    path: '/me-host-list',
    name: 'MeHostList',
    component: () => import('@/pages/me/me-host-list.vue'),
    meta: { title: '开发者模式' },
  },
]
