export const CLASSIFY_EXECL = [
  { classify: '100', classifyName: '灯光' },
  { classify: '101', classifyName: '窗帘' },
  { classify: '102', classifyName: '空调' },
  { classify: '103', classifyName: '地暖' },
  { classify: '104', classifyName: '新风' },
  { classify: '105', classifyName: '音乐' },
]

export const TYPE_EXECL = [
  { category: '100001', categoryName: '开关灯' },
  { category: '100002', categoryName: '调光灯' },
  { category: '100003', categoryName: '色温灯' },
  { category: '100004', categoryName: 'RGBW' },
  { category: '101001', categoryName: '开关窗帘' },
  { category: '101002', categoryName: '开关停窗帘' },
  { category: '101003', categoryName: '百分比窗帘' },
  { category: '101004', categoryName: '调角窗帘' },
  { category: '101005', categoryName: '杜亚窗帘电机' },
  { category: '101006', categoryName: '奥科窗帘电机' },
  { category: '101007', categoryName: '威士达窗帘电机' },
  { category: '101008', categoryName: '创明窗帘电机' },
  { category: '102001', categoryName: '开关空调' },
  { category: '102002', categoryName: '空调' },
  { category: '102003', categoryName: 'HAVC' },
  { category: '102004', categoryName: '大金空调' },
  { category: '102005', categoryName: '日立空调' },
  { category: '102006', categoryName: '红外空调' },
  { category: '102007', categoryName: '红外空调' },
  { category: '103001', categoryName: '开关地暖' },
  { category: '103002', categoryName: '地暖' },
  { category: '103003', categoryName: '阀门地暖' },
  { category: '103004', categoryName: '菲斯曼地暖' },
  { category: '103005', categoryName: '丹佛斯地暖' },
  { category: '104001', categoryName: '开关新风' },
  { category: '104002', categoryName: '新风' },
  { category: '104003', categoryName: '新风(无风速)' },
  { category: '104004', categoryName: '新风(无模式)' },
  { category: '104005', categoryName: '海克新风' },
  { category: '104006', categoryName: '日立新风' },
  { category: '104007', categoryName: '霍尼新风' },
  { category: '104008', categoryName: '霍尼CF1新风' },
  { category: '105001', categoryName: '音乐' },
  { category: '105002', categoryName: '简单音乐(带分区)' },
  { category: '105003', categoryName: '简单音乐(不带分区)' },
].map((item) => ({ ...item, classifyId: item.category.slice(0, 3) }))

export const TYPE_VALUE_EXECL = [
  {
    category: '100001',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '100001',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '100002',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '100002',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '100002',
    attr: 'brightness',
    attrName: '亮度',
    attrEn: 'brightness',
    attrCn: '亮度',
    attrValue: '1',
    attrValueRange: '0,100',
  },
  {
    category: '100003',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '100003',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '100003',
    attr: 'brightness',
    attrName: '亮度',
    attrEn: 'brightness',
    attrCn: '亮度',
    attrValue: '1',
    attrValueRange: '0,100',
  },
  {
    category: '100003',
    attr: 'colourTemperature',
    attrName: '色温',
    attrEn: 'colourTemperature',
    attrCn: '色温',
    attrValue: '1',
    attrValueRange: '1800,6000',
  },
  {
    category: '100004',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '100004',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '100004',
    attr: 'brightness',
    attrName: '亮度',
    attrEn: 'brightness',
    attrCn: '亮度',
    attrValue: '1',
    attrValueRange: '0,100',
  },
  {
    category: '100004',
    attr: 'color',
    attrName: '颜色',
    attrEn: 'color',
    attrCn: '颜色',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '100004',
    attr: 'R',
    attrName: '红色',
    attrEn: 'R',
    attrCn: '红色',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '100004',
    attr: 'G',
    attrName: '绿色',
    attrEn: 'G',
    attrCn: '绿色',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '100004',
    attr: 'B',
    attrName: '蓝色',
    attrEn: 'B',
    attrCn: '蓝色',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '100004',
    attr: 'W',
    attrName: '白色',
    attrEn: 'W',
    attrCn: '白色',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '101001',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101001',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101002',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101002',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101002',
    attr: 'stop',
    attrName: '停止',
    attrEn: 'stop',
    attrCn: '停止',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101003',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101003',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101003',
    attr: 'stop',
    attrName: '停止',
    attrEn: 'stop',
    attrCn: '停止',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101003',
    attr: 'percent',
    attrName: '百分比',
    attrEn: 'percent',
    attrCn: '百分比',
    attrValue: '1',
    attrValueRange: '0,100',
  },
  {
    category: '101004',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101004',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101004',
    attr: 'stop',
    attrName: '停止',
    attrEn: 'stop',
    attrCn: '停止',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101004',
    attr: 'angle',
    attrName: '角度',
    attrEn: 'angle',
    attrCn: '角度',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '101005',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101005',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101005',
    attr: 'stop',
    attrName: '停止',
    attrEn: 'stop',
    attrCn: '停止',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101005',
    attr: 'percent',
    attrName: '百分比',
    attrEn: 'percent',
    attrCn: '百分比',
    attrValue: '1',
    attrValueRange: '0,100',
  },
  {
    category: '101006',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101006',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101006',
    attr: 'stop',
    attrName: '停止',
    attrEn: 'stop',
    attrCn: '停止',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101007',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101007',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101007',
    attr: 'stop',
    attrName: '停止',
    attrEn: 'stop',
    attrCn: '停止',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '101007',
    attr: 'percent',
    attrName: '百分比',
    attrEn: 'percent',
    attrCn: '百分比',
    attrValue: '1',
    attrValueRange: '0,100',
  },
  {
    category: '102001',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102001',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'auto',
    attrCn: '自动风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'high',
    attrCn: '高风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'mid',
    attrCn: '中风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'low',
    attrCn: '低风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'auto',
    attrCn: '自动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'cool',
    attrCn: '制冷模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'hot',
    attrCn: '制热模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'wind',
    attrCn: '通风模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'wet',
    attrCn: '除湿模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102002',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'setTemperature',
    attrCn: '设置温度',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '102002',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'currentTemperature',
    attrCn: '环境问题',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '102003',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'valueSwitch',
    attrName: '阀门开关',
    attrEn: 'on',
    attrCn: '阀门开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'valueSwitch',
    attrName: '阀门开关',
    attrEn: 'off',
    attrCn: '阀门关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'auto',
    attrCn: '自动风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'high',
    attrCn: '高风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'mid',
    attrCn: '中风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'low',
    attrCn: '低风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'auto',
    attrCn: '自动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'cool',
    attrCn: '制冷模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'hot',
    attrCn: '制热模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'wind',
    attrCn: '通风模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'wet',
    attrCn: '除湿模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102003',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'setTemperature',
    attrCn: '设置温度',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '102003',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'currentTemperature',
    attrCn: '环境问题',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '102004',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102004',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102004',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'auto',
    attrCn: '自动风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102004',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'high',
    attrCn: '高风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102004',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'mid',
    attrCn: '中风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102004',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'low',
    attrCn: '低风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102004',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'auto',
    attrCn: '自动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102004',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'cool',
    attrCn: '制冷模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102004',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'hot',
    attrCn: '制热模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102004',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'wind',
    attrCn: '通风模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102004',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'wet',
    attrCn: '除湿模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102004',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'setTemperature',
    attrCn: '设置温度',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '102004',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'currentTemperature',
    attrCn: '环境问题',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '102005',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102005',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102005',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'auto',
    attrCn: '自动风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102005',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'high',
    attrCn: '高风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102005',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'mid',
    attrCn: '中风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102005',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'low',
    attrCn: '低风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'auto',
    attrCn: '自动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'cool',
    attrCn: '制冷模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'hot',
    attrCn: '制热模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'wind',
    attrCn: '通风模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'wet',
    attrCn: '除湿模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '102005',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'setTemperature',
    attrCn: '设置温度',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '102005',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'currentTemperature',
    attrCn: '环境问题',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '103001',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103001',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103002',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103002',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'day',
    attrCn: '白天模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'night',
    attrCn: '夜晚模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'leave',
    attrCn: '离家模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'auto',
    attrCn: '自动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'manual',
    attrCn: '手动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103002',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'setTemperature',
    attrCn: '设置温度',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '103002',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'currentTemperature',
    attrCn: '环境问题',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '103003',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103003',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103003',
    attr: 'valueSwitch',
    attrName: '阀门开关',
    attrEn: 'on',
    attrCn: '阀门开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103003',
    attr: 'valueSwitch',
    attrName: '阀门开关',
    attrEn: 'off',
    attrCn: '阀门关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'day',
    attrCn: '白天模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'night',
    attrCn: '夜晚模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'leave',
    attrCn: '离家模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'auto',
    attrCn: '自动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'manual',
    attrCn: '手动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103003',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'setTemperature',
    attrCn: '设置温度',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '103003',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'currentTemperature',
    attrCn: '环境问题',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '103004',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103004',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103004',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'setTemperature',
    attrCn: '设置温度',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '103004',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'currentTemperature',
    attrCn: '环境问题',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '103005',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103005',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'day',
    attrCn: '白天模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'night',
    attrCn: '夜晚模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'leave',
    attrCn: '离家模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'auto',
    attrCn: '自动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'manual',
    attrCn: '手动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '103005',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'setTemperature',
    attrCn: '设置温度',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '103005',
    attr: 'temperature',
    attrName: '温度',
    attrEn: 'currentTemperature',
    attrCn: '环境问题',
    attrValue: '1',
    attrValueRange: '16,32',
  },
  {
    category: '104001',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104001',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104002',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104002',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'fresh',
    attrCn: '新风模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'constant',
    attrCn: '横温模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'loop',
    attrCn: '循环模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104002',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'auto',
    attrCn: '自动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104002',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'auto',
    attrCn: '自动风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104002',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'high',
    attrCn: '高风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104002',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'mid',
    attrCn: '中风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104002',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'low',
    attrCn: '低风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104003',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104003',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'fresh',
    attrCn: '新风模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'constant',
    attrCn: '横温模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'loop',
    attrCn: '循环模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104003',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'auto',
    attrCn: '自动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104004',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104004',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104004',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'auto',
    attrCn: '自动风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104004',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'high',
    attrCn: '高风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104004',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'mid',
    attrCn: '中风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104004',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'low',
    attrCn: '低风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104005',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104005',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'fresh',
    attrCn: '新风模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'constant',
    attrCn: '横温模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'loop',
    attrCn: '循环模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104005',
    attr: 'mode',
    attrName: '模式',
    attrEn: 'auto',
    attrCn: '自动模式',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104005',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'auto',
    attrCn: '自动风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104005',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'high',
    attrCn: '高风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104005',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'mid',
    attrCn: '中风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104005',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'low',
    attrCn: '低风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104006',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104006',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104006',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'high',
    attrCn: '高风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104006',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'mid',
    attrCn: '中风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104006',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'low',
    attrCn: '低风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104007',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104007',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104007',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'high',
    attrCn: '高风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104007',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'mid',
    attrCn: '中风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104007',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'low',
    attrCn: '低风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104008',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'on',
    attrCn: '开',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104008',
    attr: 'switch',
    attrName: '开关',
    attrEn: 'off',
    attrCn: '关',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104008',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'auto',
    attrCn: '自动风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104008',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'high',
    attrCn: '高风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104008',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'mid',
    attrCn: '中风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '104008',
    attr: 'fan',
    attrName: '风速',
    attrEn: 'low',
    attrCn: '低风速',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'playControl',
    attrName: '播放控制',
    attrEn: 'play',
    attrCn: '播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'playControl',
    attrName: '播放控制',
    attrEn: 'pause',
    attrCn: '暂停',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'cutSong',
    attrName: '切歌',
    attrEn: 'prev',
    attrCn: '上一首',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'cutSong',
    attrName: '切歌',
    attrEn: 'next',
    attrCn: '下一首',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'list',
    attrCn: '列表播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'sequence',
    attrCn: '顺序播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'single',
    attrCn: '随机播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'random',
    attrCn: '单曲循环',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'loop',
    attrCn: '列表循环',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'volume',
    attrName: '音量控制',
    attrEn: 'up',
    attrCn: '音量加',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'volume',
    attrName: '音量控制',
    attrEn: 'down',
    attrCn: '音量减',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'volume',
    attrName: '音量控制',
    attrEn: 'volume',
    attrCn: '设置音量',
    attrValue: '1',
    attrValueRange: '0,100',
  },
  {
    category: '105001',
    attr: 'process',
    attrName: '播放进度',
    attrEn: 'process',
    attrCn: '播放进度',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'list',
    attrName: '歌曲列表',
    attrEn: 'list',
    attrCn: '歌曲列表',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'source',
    attrName: '音源',
    attrEn: 'usb',
    attrCn: 'U盘播放',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'source',
    attrName: '音源',
    attrEn: 'local',
    attrCn: '本地播放',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'source',
    attrName: '音源',
    attrEn: 'fm',
    attrCn: 'FM',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'source',
    attrName: '音源',
    attrEn: 'cloud',
    attrCn: '云音乐',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105001',
    attr: 'tunnels',
    attrName: '分区',
    attrEn: 'tunnels',
    attrCn: '分区',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'playControl',
    attrName: '播放控制',
    attrEn: 'play',
    attrCn: '播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'playControl',
    attrName: '播放控制',
    attrEn: 'pause',
    attrCn: '暂停',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'cutSong',
    attrName: '切歌',
    attrEn: 'prev',
    attrCn: '上一首',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'cutSong',
    attrName: '切歌',
    attrEn: 'next',
    attrCn: '下一首',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'list',
    attrCn: '列表播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'sequence',
    attrCn: '顺序播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'single',
    attrCn: '随机播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'random',
    attrCn: '单曲循环',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'loop',
    attrCn: '列表循环',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'volume',
    attrName: '音量控制',
    attrEn: 'up',
    attrCn: '音量加',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'volume',
    attrName: '音量控制',
    attrEn: 'down',
    attrCn: '音量减',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105002',
    attr: 'volume',
    attrName: '音量控制',
    attrEn: 'volume',
    attrCn: '设置音量',
    attrValue: '1',
    attrValueRange: '0,100',
  },
  {
    category: '105002',
    attr: 'tunnels',
    attrName: '分区',
    attrEn: 'tunnels',
    attrCn: '分区',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'playControl',
    attrName: '播放控制',
    attrEn: 'play',
    attrCn: '播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'playControl',
    attrName: '播放控制',
    attrEn: 'pause',
    attrCn: '暂停',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'cutSong',
    attrName: '切歌',
    attrEn: 'prev',
    attrCn: '上一首',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'cutSong',
    attrName: '切歌',
    attrEn: 'next',
    attrCn: '下一首',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'list',
    attrCn: '列表播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'sequence',
    attrCn: '顺序播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'single',
    attrCn: '随机播放',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'random',
    attrCn: '单曲循环',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'mode',
    attrName: '播放模式',
    attrEn: 'loop',
    attrCn: '列表循环',
    attrValue: '0',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'volume',
    attrName: '音量控制',
    attrEn: 'up',
    attrCn: '音量加',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'volume',
    attrName: '音量控制',
    attrEn: 'down',
    attrCn: '音量减',
    attrValue: '1',
    attrValueRange: '',
  },
  {
    category: '105003',
    attr: 'volume',
    attrName: '音量控制',
    attrEn: 'volume',
    attrCn: '设置音量',
    attrValue: '1',
    attrValueRange: '0,100',
  },
]

const switchColumn = {
  text: '开关',
  value: 'switch',
  children: [
    { text: '开', value: 'on' },
    { text: '关', value: 'off' },
  ],
}

const brightnessColumn = {
  text: '亮度',
  value: 'brightness',
}

const colourTemperatureColumn = {
  text: '色温',
  value: 'colourTemperature',
}
const colourColumn = {
  text: '颜色',
  value: 'color',
  children: [
    { text: '红色', value: 'R' },
    { text: '绿色', value: 'G' },
    { text: '蓝色', value: 'B' },
    { text: '白色', value: 'W' },
  ],
}

const stopColumn = { text: '停', value: 'stop' }

const percentColumn = { text: '百分比', value: 'percent' }

const angleColumn = { text: '角度', value: 'angle' }

const fanColumn = {
  text: '风速',
  value: 'fan',
  children: [
    { text: '自动风速', value: 'auto' },
    { text: '高风速', value: 'high' },
    { text: '中风速', value: 'mid' },
    { text: '低风速', value: 'low' },
  ],
}

const airModeColumn = {
  text: '模式',
  value: 'mode',
  children: [
    { text: '自动模式', value: 'auto' },
    { text: '制冷模式', value: 'cool' },
    { text: '制热模式', value: 'hot' },
    { text: '通风模式', value: 'wind' },
    { text: '除湿模式', value: 'wet' },
  ],
}

const temperatureColumn = {
  text: '温度',
  value: 'temperature',
  children: [
    { text: '设置温度', value: 'setTemperature' },
    { text: '环境问题', value: 'currentTemperature' },
  ],
}

const codeColumn = {
  text: '代码',
  value: 'code',
  children: [{ text: '故障代码', value: 'code' }],
}

const underfloorModeColumn = {
  text: '模式',
  value: 'mode',
  children: [
    { text: '白天模式', value: 'day' },
    { text: '夜晚模式', value: 'night' },
    { text: '离家模式', value: 'leave' },
    { text: '自动模式', value: 'atuo' },
    { text: '手动模式', value: 'manual' },
  ],
}
const freshModeColumn = {
  text: '模式',
  value: 'mode',
  children: [
    { text: '新风模式', value: 'fresh' },
    { text: '横温模式', value: 'constant' },
    { text: '循环模式', value: 'loop' },
    { text: '自动模式', value: 'atuo' },
  ],
}

const palyColumn = {
  text: '播放控制',
  value: 'palyControl',
  children: [
    { text: '播放', value: 'play' },
    { text: '暂停', value: 'pause' },
  ],
}

const cutSongColumn = {
  text: '切歌',
  value: 'cutSong',
  children: [
    { text: '上一首', value: 'prev' },
    { text: '下一首', value: 'next' },
  ],
}

const musicModeColumn = {
  text: ' 播放模式 ',
  value: 'mode',
  children: [
    { text: '列表播放', value: 'list' },
    { text: '顺序播放', value: 'sequence' },
    { text: '随机播放', value: 'single' },
    { text: '单曲循环', value: 'random' },
    { text: '列表循环', value: 'loop' },
  ],
}

const volumeColumn = {
  text: ' 音量控制 ',
  value: 'volume',
  children: [
    { text: '音量加', value: 'up' },
    { text: '音量减', value: 'down' },
    { text: '设置音量', value: 'volume' },
  ],
}

const processColumn = {
  text: ' 进度 ',
  value: 'process',
  children: [{ text: '播放进度', value: 'process' }],
}

const listColumn = {
  text: ' 列表 ',
  value: 'list',
  children: [{ text: '歌曲列表', value: 'list' }],
}

const sourceColumn = {
  text: ' 音源 ',
  value: 'source',
  children: [
    { text: 'U盘播放', value: 'usb' },
    { text: '本地播放', value: 'local' },
    { text: 'FM', value: 'fm' },
    { text: '云音乐', value: 'cloud' },
  ],
}

const tunnelsColumn = {
  text: ' 分区 ',
  value: 'tunnels',
}

export default [
  {
    name: 'lamp',
    text: '灯',
    classify: '100',
    category: ['100001', '100002', '100003', '100004'],
    icon: 'tips',
    100001: switchColumn,
    100002: {
      aliasName: '调光灯',
      columns: [switchColumn, brightnessColumn],
    },
    100003: {
      aliasName: '色温灯',
      columns: [switchColumn, brightnessColumn, colourTemperatureColumn],
    },
    100004: {
      aliasName: 'RGBW',
      columns: [switchColumn, brightnessColumn, colourColumn],
    },
  },
  {
    name: 'curtain',
    text: '窗帘',
    classify: '101',
    category: ['101001', '101002', '101003', '101004', '101005', '101006', '101007', '101008'],
    icon: 'rectangle-tear',
    101001: {
      aliasName: '开关窗帘',
      columns: [switchColumn],
    },
    101002: {
      aliasName: '开关停窗帘',
      columns: [switchColumn, stopColumn],
    },
    101003: {
      aliasName: '百分比窗帘',
      columns: [switchColumn, stopColumn, percentColumn],
    },
    101004: {
      aliasName: '调角窗帘',
      columns: [switchColumn, stopColumn, angleColumn],
    },
    101005: {
      aliasName: '杜亚窗帘电机',
      columns: [switchColumn, stopColumn, percentColumn],
    },
    101006: {
      aliasName: '奥科窗帘电机',
      columns: [switchColumn, stopColumn, percentColumn],
    },
    101007: {
      aliasName: '威士达窗帘电机',
      columns: [switchColumn, stopColumn, percentColumn],
    },
    101008: {
      aliasName: '创明窗帘电机',
      columns: [switchColumn, stopColumn, percentColumn],
    },
  },
  {
    name: 'ariCooler',
    text: '空调',
    classify: '102',
    category: ['102001', '102002', '102003', '102004', '102005'],
    icon: 'air-conditioning',
    102001: {
      aliasName: '简易空调',
      columns: [switchColumn],
    },
    102002: {
      aliasName: '常规空调',
      columns: [switchColumn, fanColumn, airModeColumn, temperatureColumn, codeColumn],
    },
    102003: {
      aliasName: 'HAVC空调',
      columns: [
        switchColumn,
        { ...switchColumn, text: '阀门开关', value: 'valueSwitch' },
        fanColumn,
        airModeColumn,
        temperatureColumn,
        codeColumn,
      ],
    },
    102004: {
      aliasName: '大金空调',
      columns: [switchColumn, fanColumn, airModeColumn, temperatureColumn, codeColumn],
    },
    102005: {
      aliasName: '日立空调',
      columns: [switchColumn, fanColumn, airModeColumn, temperatureColumn, codeColumn],
    },
  },
  {
    name: 'underfloorHeat',
    text: '地暖',
    classify: '103',
    category: ['103001', '103002', '103003'],
    icon: 'boiler',
    103001: {
      aliasName: '简易地暖',
      columns: [switchColumn],
    },
    103002: {
      aliasName: '常规地暖',
      columns: [switchColumn, underfloorModeColumn, temperatureColumn],
    },
    103003: {
      aliasName: '阀门地暖',
      columns: [
        switchColumn,
        { ...switchColumn, text: '阀门开关', value: 'valueSwitch' },
        underfloorModeColumn,
        temperatureColumn,
      ],
    },
  },
  {
    name: 'freshAir',
    text: '新风',
    classify: '104',
    category: ['104001', '104002', '104003', '104004'],
    icon: 'whirlwind',
    104001: {
      aliasName: '开关新风',
      columns: [switchColumn],
    },
    104002: {
      aliasName: '常规新风',
      columns: [switchColumn, freshModeColumn, fanColumn],
    },
    104003: {
      aliasName: '无风速新风',
      columns: [switchColumn, freshModeColumn],
    },
    104004: {
      aliasName: '无模式新风',
      columns: [switchColumn, fanColumn],
    },
  },
  {
    name: 'music',
    text: '音乐',
    classify: '105',
    category: ['105001', '105002', '105003'],
    icon: 'music',
    105001: {
      aliasName: '全功能音乐',
      columns: [
        palyColumn,
        cutSongColumn,
        musicModeColumn,
        volumeColumn,
        processColumn,
        listColumn,
        sourceColumn,
        tunnelsColumn,
      ],
    },
    105002: {
      aliasName: '普通音乐带分区',
      columns: [palyColumn, cutSongColumn, musicModeColumn, volumeColumn, tunnelsColumn],
    },
    105003: {
      aliasName: '普通音乐不带分区',
      columns: [palyColumn, cutSongColumn, musicModeColumn, volumeColumn],
    },
  },
]
