export const MIME_TYPES = {
  '.apk': 'application/vnd.android.package-archive',
  '.bin': 'application/octet-stream',
  '.class': 'application/octet-stream',
  '.doc': 'application/msword',
  '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.xls': 'application/vnd.ms-excel',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.exe': 'application/octet-stream',
  '.gtar': 'application/x-gtar',
  '.gz': 'application/x-gzip',
  '.jar': 'application/java-archive',
  '.js': 'application/x-javascript',
  '.mpc': 'application/vnd.mpohun.certificate',
  '.msg': 'application/vnd.ms-outlook',
  '.pdf': 'application/pdf',
  '.pps': 'application/vnd.ms-powerpoint',
  '.ppt': 'application/vnd.ms-powerpoint',
  '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  '.rtf': 'application/rtf',
  '.tar': 'application/x-tar',
  '.tgz': 'application/x-compressed',
  '.wps': 'application/vnd.ms-works',
  '.z': 'application/x-compress',
  '.zip': 'application/x-zip-compressed',
}

export const AUDIO_TYPES = {
  '.m3u': 'audio/x-mpegurl',
  '.m4a': 'audio/mp4a-latm',
  '.m4b': 'audio/mp4a-latm',
  '.m4p': 'audio/mp4a-latm',
  '.mp2': 'audio/x-mpeg',
  '.mp3': 'audio/x-mpeg',
  '.mpga': 'audio/mpeg',
  '.rmvb': 'audio/x-pn-realaudio',
  '.wav': 'audio/x-wav',
  '.wma': 'audio/x-ms-wma',
  '.wmv': 'audio/x-ms-wmv',
  '.ogg': 'audio/ogg',
}

export const IMAGE_TYPES = {
  '.bmp': 'image/bmp',
  '.gif': 'image/gif',
  '.jpeg': 'image/jpeg',
  '.jpg': 'image/jpeg',
  '.png': 'image/png',

  // '.tif': 'image/tif',
  // '.pcx': 'image/pcx',
  // '.tga': 'image/tga',
  // '.exif': 'image/exif',
  // '.fpx': 'image/fpx',
  // '.svg': 'image/svg',
  // '.psd': 'image/psd',
  // '.cdr': 'image/cdr',
  // '.pcd': 'image/pcd',
  // '.dxf': 'image/dxf',
  // '.ufo': 'image/ufo',
  // '.eps': 'image/eps',
  // '.ai': 'image/ai',
  // '.raw': 'image/raw',
  // '.wmf': 'image/wmf',
  // '.webp': 'image/webp',
  // '.avif': 'image/avif',
  // '.apng': 'image/apng',
}

export const VIDEO_TYPES = {
  '.3gp': 'video/3gpp',
  '.asf': 'video/x-ms-asf',
  '.avi': 'video/x-msvideo',
  '.m4u': 'video/vnd.mpegurl',
  '.m4v': 'video/x-m4v',
  '.mov': 'video/quicktime',
  '.mp4': 'video/mp4',
  '.mpe': 'video/mpeg',
  '.mpeg': 'video/mpeg',
  '.mpg': 'video/mpeg',
  '.mpg4': 'video/mp4',
}

export const TEXT_TYPES = {
  '.c': 'text/plain',
  '.conf': 'text/plain',
  '.cpp': 'text/plain',
  '.h': 'text/plain',
  '.htm': 'text/html',
  '.html': 'text/html',
  '.java': 'text/plain',
  '.log': 'text/plain',
  '.prop': 'text/plain',
  '.rc': 'text/plain',
  '.sh': 'text/plain',
  '.txt': 'text/plain',
  '.xml': 'text/plain',
}

export const FILE_TYPE = {
  '': '*/*',
  ...MIME_TYPES,
  ...AUDIO_TYPES,
  ...IMAGE_TYPES,
  ...VIDEO_TYPES,
  ...TEXT_TYPES,
}
