import {
  Button,
  Cell,
  CellGroup,
  Icon,
  Image as VanImage,
  Col,
  Row,
  Popup,
  Space,
  Calendar,
  Cascader,
  Checkbox,
  CheckboxGroup,
  DatePicker,
  Field,
  Form,
  Picker,
  PickerGroup,
  RadioGroup,
  Radio,
  Rate,
  Search,
  Slider,
  Stepper,
  Switch,
  TimePicker,
  Uploader,
  ActionSheet,
  DropdownMenu,
  DropdownItem,
  Loading,
  Overlay,
  PullRefresh,
  ShareSheet,
  SwipeCell,
  Badge,
  Circle,
  Collapse,
  CollapseItem,
  CountDown,
  Divider,
  Empty,
  ImagePreview,
  Lazyload,
  List,
  NoticeBar,
  Popover,
  Progress,
  Skeleton,
  SkeletonTitle,
  SkeletonImage,
  SkeletonAvatar,
  SkeletonParagraph,
  Step,
  Steps,
  Sticky,
  Swipe,
  SwipeItem,
  Tag,
  ActionBar,
  ActionBarIcon,
  ActionBarButton,
  Grid,
  GridItem,
  IndexBar,
  IndexAnchor,
  NavBar,
  Pagination,
  Sidebar,
  SidebarItem,
  Tab,
  Tabs,
  Tabbar,
  TabbarItem,
  TreeSelect,
  BackTop,
  Area,
  Card,
  Toast,
  Dialog,
  Notify,
} from 'vant'

export function useVant(app) {
  app
    .use(Button)
    .use(Cell)
    .use(CellGroup)
    .use(Icon)
    .use(VanImage)
    .use(Col)
    .use(Row)
    .use(Popup)
    .use(Space)
    .use(Calendar)
    .use(Cascader)
    .use(Checkbox)
    .use(CheckboxGroup)
    .use(DatePicker)
    .use(Field)
    .use(Form)
    .use(Picker)
    .use(PickerGroup)
    .use(RadioGroup)
    .use(Radio)
    .use(Rate)
    .use(Search)
    .use(Slider)
    .use(Stepper)
    .use(Switch)
    .use(TimePicker)
    .use(Uploader)
    .use(ActionSheet)
    .use(DropdownMenu)
    .use(DropdownItem)
    .use(Loading)
    .use(Overlay)
    .use(PullRefresh)
    .use(ShareSheet)
    .use(SwipeCell)
    .use(Badge)
    .use(Circle)
    .use(Collapse)
    .use(CollapseItem)
    .use(CountDown)
    .use(Divider)
    .use(Empty)
    .use(ImagePreview)
    .use(Lazyload)
    .use(List)
    .use(NoticeBar)
    .use(Popover)
    .use(Progress)
    .use(Skeleton)
    .use(SkeletonTitle)
    .use(SkeletonImage)
    .use(SkeletonAvatar)
    .use(SkeletonParagraph)
    .use(Step)
    .use(Steps)
    .use(Sticky)
    .use(Swipe)
    .use(SwipeItem)
    .use(Tag)
    .use(ActionBar)
    .use(ActionBarIcon)
    .use(ActionBarButton)
    .use(Grid)
    .use(GridItem)
    .use(IndexBar)
    .use(IndexAnchor)
    .use(NavBar)
    .use(Pagination)
    .use(Sidebar)
    .use(SidebarItem)
    .use(Tab)
    .use(Tabs)
    .use(Tabbar)
    .use(TabbarItem)
    .use(TreeSelect)
    .use(BackTop)
    .use(Area)
    .use(Card)
    .use(Toast)
    .use(Dialog)
    .use(Notify)
}
